const products = [
  {
    id: 1,
    img: './image/01.png',
    title: 'Apple BYZ S852I',
    price: 3527,
    discount: 2927,
    rate: 4.7,
  },
  {
    id: 2,
    img: './image/02.png',
    title: 'Apple EarPods',
    price: 2327,
    discount: 0,
    rate: 4.5,
  },
  {
    id: 3,
    img: './image/03.png',
    title: 'Apple EarPods',
    price: 2327,
    discount: 0,
    rate: 4.5,
  },
  {
    id: 4,
    img: './image/04.png',
    title: 'Apple AirPods',
    price: 9527,
    discount: 0,
    rate: 4.7,
  },
  {
    id: 5,
    img: './image/05.png',
    title: 'GERLAX GH-04',
    price: 6527,
    discount: 0,
    rate: 4.7,
  },
  {
    id: 6,
    img: './image/06.png',
    title: 'BOROFONE BO4',
    price: 7527,
    discount: 0,
    rate: 4.7,
  },
]
export default products
